### ISSUE TITLE
rcn-ee_console_ubuntu_focal_armhf permission issues

### ISSUE THREAD

**Issue by drmpeg** [RobertCNelson/omap-image-builder#129] opened 2020-04-26 03:34 UTC
I'm getting some permission errors running ./RootStock-NG.sh -c rcn-ee_console_ubuntu_focal_armhf.
```
W: Download is performed unsandboxed as root as file '/var/lib/apt/lists/partial/ports.ubuntu.com_dists_focal_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/bb-usb-gadgets_1.20200322.1-0~focal+20200424_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/libpruio-modules-4.19.94-ti-r43_1focal_armhf.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```
and a few more.

BTW, no rush on this. I'm just trying to help out with the debugging.

**Comment by RobertCNelson** [comment] 2020-04-26 03:39
Just anther duplicate of https://github.com/RobertCNelson/omap-image-builder/issues/108

Not a bug, just apt complaining..

**Closed by RobertCNelson** 2020-04-26 03:39 UTC
